### ISSUE TITLE
перевірки

### ISSUE THREAD

**Issue by pecourses** [VasylUlianovskyi/Class-syntax#1]
https://github.com/VasylUlianovskyi/Class-syntax/blob/93c4be4b64c6b900d8b8f55f251e06a29afadd5c/assets/js/index.js#L177
- тут, мабуть, мала бути перевірка типу даних

**Comment by VasylUlianovskyi** [comment]
++

**Comment by pecourses** [comment]
Мимо)

**Comment by pecourses** [comment]
- спробуйте для себе сформулювати, що саме тут перевіряється або має перевірятися. + перевірити, чи працює на зараз цей метод

**Comment by VasylUlianovskyi** [comment]
Зрозумів де помилка, я перевіряв масив, а потрібно було перевірити вміст

**Comment by pecourses** [comment]
+ плюс перевіряється тип, а не саме значення
